CREATE DATABASE IF NOT EXISTS SALES_DB;

USE DATABASE SALES_DB;

CREATE SCHEMA IF NOT EXISTS RAW;

CREATE TABLE IF NOT EXISTS RAW.SALES
(
ORDER_ID INTEGER,
CUSTOMER_ID STRING,
PRODUCT STRING,
CATEGORY STRING,
QUANTITY INTEGER,
PRICE NUMBER,
REGION STRING,
ORDER_DATE DATE,
TOTAL_AMOUNT NUMBER
);
